Issue #89 - Environment setup script
graph-algorithms/edge-addition-planarity-suite pull request #112
Opened 2024-10-25 23:39 UTC by wbkboyer

Resolves #89 

## Added
* `devEnvSetupAndDefaults/`
  * `devEnvSetup.sh` - copies default configuration files to expected target locations
  * `.vscode/` - contains default configuration files for `tasks.json`, `launch.json`, and `settings.json` (see #16 , #58 , and #92 )
  * `TestSupport/planaritytesting/`
    * `leaksorchestrator/planarity_leaks_config.ini` - Default configuration file for `TestSupport/planaritytesting/leaksorchestrator/planarity_leaks_orchestrator.py` script, generated by `planarity_leaks_config_manager.py` (see #59 and #81)
    * `.pylintrc` - configures (#100 will add more complete documentation to the [2. Dev Setup](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/2.-Dev-Setup) wiki page)

## Updated
* `.gitignore` - ignore `.vscode` directory when it appears at *root* of repository; ignore Eclipse configuration files (if present); ignore `.pylintrc` and `planarity_leaks_config.ini` under `TestSupport/` directory
* `README.md` - Extracted development environment setup instructions and now refer to [2. Dev Setup](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/2.-Dev-Setup) wiki page; minor tweaks and clarifications

## Removed
* `.cproject`, `.project`, and `c/.cproject` Eclipse IDE configuration files

2024-10-30 23:36 UTC, john-boyer-phd requested changes
Aside from a few minor tweaks given inline, let's discuss the following in stand-up tomorrow:
1. The PR shows the removal of the eclipse project files (good) but it doesn't seem to show me the removal of the VS code json files that are now templatized in the `devEnvSetupAndDefaults` directory. What will cause the non-templatized ones to be removed from master when this PR is merged?
2. In the `devEnvSetupAndDefaults`, there is now a `settings.json`, but there doesn't seem to be one in the old non-templatized `.vscode` directory. It's undoubtedly a good idea to be adding one, but I'd just like to talk through what it is contributing that we didn't have  across dev environments before.

2024-10-30 23:36 UTC, john-boyer-phd commented on README.md
> +On several (Debian-based) distributions of Linux, you may be able to get the planarity executable with `sudo apt install planarity`, or you may already have it you have Matlab. For non-developer Wind
... you may already have it _if_ you have Matlab...

2024-10-30 23:36 UTC, john-boyer-phd commented on README.md
> +The `planarity` executable program also supports an extensive list of command-line parameters that make it possible to automate the execution of any of the algorithms included in the application. Run
Thanks for fixing all of the underscored items to put tick marks around them.

2024-10-30 23:36 UTC, john-boyer-phd commented on README.md
> +Please refer to the [2. Dev Setup](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/2.-Dev-Setup) wiki page for instructions on how to install development dependencies on Window
The readme should probably leave the versions of OS's to the wiki page. Also, on the wiki page, I think it's going to be reasonable to include Windows 11 not just Windows 10 22H2 (but that is a discussion about the wiki page that can happen outside of PR land).

2024-10-30 23:36 UTC, john-boyer-phd commented on README.md
> +You also don't necessarily need to `make` and `make install` the planarity software on Linux if you are able to get it using `sudo apt planarity` (i.e. are using a Debian-based Linux distribution whi
... (i.e., using... [add comma, remove "are"]

2024-10-31 16:25 UTC, wbkboyer commented
> Aside from a few minor tweaks given inline, let's discuss the following in stand-up tomorrow:
> 
> 1. The PR shows the removal of the eclipse project files (good) but it doesn't seem to show me the removal of the VS code json files that are now templatized in the `devEnvSetupAndDefaults` directory. What will cause the non-templatized ones to be removed from master when this PR is merged?

I did run `git rm --cached -r .vscode/`, but I think since I'm including the files in the `devEnvSetupAndDefaults/` directory, it's counting those files as "renamed" 🚀 

> 2. In the `devEnvSetupAndDefaults`, there is now a `settings.json`, but there doesn't seem to be one in the old non-templatized `.vscode` directory. It's undoubtedly a good idea to be adding one, but I'd just like to talk through what it is contributing that we didn't have  across dev environments before.

The workings of `settings.json` will be documented in [2. Dev Setup](https://github.com/graph-algorithms/edge-addition-planarity-suite/wiki/2.-Dev-Setup) as part of #100 🎉

2024-10-31 16:26 UTC, john-boyer-phd approved these changes
Looks great, thanks!

2024-10-31 16:27 UTC, merged