Issue 18 - Support conversion from any format to .g6 format
graph-algorithms/edge-addition-planarity-suite pull request #41
Opened 2024-04-02 22:32 UTC by wbkboyer

Resolves #18 

## Added
* _COMING SOON_

## Updated
* _COMING SOON_

2024-04-03 17:28 UTC, wbkboyer commented on .vscode/tasks.json
> +            "label": "C/C++: gcc build active file (Linux)",
Rename to "build project"

2024-04-03 17:29 UTC, wbkboyer commented on .vscode/tasks.json
> -                "-DDEBUG", // Added so that _DEBUG is defined; see appconst.h
Restore these comments, as they were informative.

2024-04-05 17:18 UTC, john-boyer-phd requested changes
Excellent and good to go except tweaks to a few comments.

2024-04-05 17:18 UTC, john-boyer-phd commented on .vscode/launch.json
> +            "name": "C/C++: gcc build and debug active file (Linux)",
A most welcome addition!

2024-04-05 17:18 UTC, john-boyer-phd commented on .vscode/tasks.json
> +                "/DDEBUG",
The comment was nice, Would be good to have it back.

2024-04-05 17:18 UTC, john-boyer-phd commented on .vscode/tasks.json
> -                "-DDEBUG", // Added so that _DEBUG is defined; see appconst.h
:-)

2024-04-05 17:18 UTC, john-boyer-phd commented on c/graphIO.c
> +             	 if ((ErrorCode = gp_DynamicAddEdge(theGraph, v, 0, W, 0)) != OK)
Excellent

2024-04-05 17:18 UTC, john-boyer-phd commented on c/planarityCommandLine.c
> +	if (runGraphTransformationTest("-tg", "nauty_example.g6.0-based.AdjList.out.txt", TRUE) < 0)
Great to smoke test g6 writing.

2024-04-05 17:18 UTC, john-boyer-phd commented on c/planarityCommandLine.c
> +	if (inputString != NULL)
Good catch.

2024-04-05 17:18 UTC, john-boyer-phd commented on c/strOrFile.c
> + On failure, returns EOF. TODO: should we set error code?
Remove TODO. Returning EOF is the error indicator for fputs, so it is sufficient for this too.

2024-04-05 18:17 UTC, john-boyer-phd approved these changes
Looks great!

2024-04-05 18:19 UTC, merged